### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jaanos** [UrosKrampelj/Formula-1#2]
Datoteka `.RData` ne sodi v repozitorij - pobrišita jo in v `.gitignore` dodajte vrstico `.RData`, da vam te datoteke git ne bo več ponujal za dodajanje.

Mimogrede, v `.gitignore` dodajte še `auth.R` - v tej datoteki boste imeli geslo za povezavo na bazo (za ustvarjanje in polnjenje baze), tega pa seveda nočete objaviti.

**Comment by Zulkinho** [comment]
Naredil sem kot ste naročili. Upam da je sedaj vredu.

**Comment by jaanos** [comment]
V redu, bom kar zaprl zadevo.

Zadeve lahko zapirate tudi sami - bodisi s klikom na **Close issue** oziroma **Close and comment**, če obenem še kaj napišete, ali pa tako, da v sporočilo commita, ki poskrbi za zadevo, (kjerkoli) vključite `close #2`, kjer je #2 številka zadeve.
