### ISSUE TITLE
Avtentikacija

### ISSUE THREAD

**Issue by jaanos** [UrosKrampelj/Formula-1#3]
Trenutno imate na repozitoriju datoteko `auth_public.r` s podatki za prijavo z uporabnikom `javnost`. To boste vključili v končno aplikacijo, da jo bo lahko kdorkoli uporabljal. Seveda boste morali dati zadostne pravice uporabniku `javnost` - poglejte si nocmatic/prevozi#4.

V programih za uvoz namesto `auth_public.r` vključite datoteko `auth.R`, kjer naj ima vsak od vas svoje geslo za prijavo na bazo (za nastavitev zadostnih pravic si poglejte prejšnjo povezavo). To datoteko imate v `.gitignore`, tako da je git ne bo ponudil za dodajanje na repozitorij.

**Comment by Zulkinho** [comment]
Pobrisal sem auth_public.r in ko bo shiny narejen jo bom spet napisal. Pogledal sem kaj ste napisali maticu in poskusil dodeliti pravice mojima kolegoma kot ste mu napisali. Bi mi morda lahko pogledali v datoteko baza.r in mi povedali če sem to uredu naredil. Hvala !

**Comment by jaanos** [comment]
Izgleda v redu - manjkajo le še pravice za `javnost` (ampak to morda želite naredti kasneje, ko bo baza dokončana).

Mimogrede, opažam, da imate v tabeli `result` stolpec `time` tipa `VARCHAR(11)`. Da bo mogoče čase primerjati in z njimi računati, raje uporabite tip `interval` - potem lahko čase vnašate v obliki `01:23:45.678` (najmanjša resolucija je sicer na mikrosekunde, tako da bi lahko podali tudi natančnejše čase).

**Comment by Zulkinho** [comment]
hvala za nasvet

**Comment by Zulkinho** [comment]
prav tako imam težave s to tabelo result saj ko jo želim ustvariti mi napiše tole:
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  column "id" referenced in foreign key constraint does not exist
)

Pa ne vem zakaj

**Comment by Zulkinho** [comment]
Ugotovil sem kje sem se zmotil ampak mi sedaj vrže tole:  Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  there is no unique constraint matching given keys for referenced table "driver"
)

**Comment by Zulkinho** [comment]
Prav tako imam težave s polnjenjem tabel : Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near "country"
LINE 8:                                          country TEXT NOT NU...
                                                 ^
) 

Že v naprej hvala za pomoč

**Comment by jaanos** [comment]
Tuji ključi se lahko sklicujejo samo na stolpce z omejitvijo `UNIQUE` (kar vključuje glavne ključe). Ime in priimek torej odstranite iz tabele `result` - tako ali tako gre tukaj za ponovljen podatek, ki ga dobite z ustreznim `JOIN`om.

**Comment by Zulkinho** [comment]
Hvala za pomoč. Mi je jasno sedaj.
