### ISSUE TITLE
relacija

### ISSUE THREAD

**Issue by Zulkinho** [UrosKrampelj/Formula-1#5]
Dober dan .

Z Urošem imava probem pri ustvarjanju relacije "has".  Ne veva točno kako izgledajo ukazi za select in join v programu R studio. Ob najinem poizkusu pa nama je napisalo :
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbWriteTable’ for signature ‘"PostgreSQLConnection", "character", "tbl_postgres"’ .

Bi lahko prosim pogledali kaj je narobe.
Lep pozdrav

**Comment by jaanos** [comment]
Sem vam odprl pull request #6, kjer je urejen uvoz podatkov. Svetoval bi še, da nekoliko uredite podatke v rezultatih:
* uvrstitev naj bo tipa `INTEGER` - neuvrščeni naj imajo vrednost `NULL` (`NA` v R-ju)
* čas naj bo tipa `INTERVAL`; zaostanke pretvorite v čase (prištejte času zmagovalca), ostali naj imajo vrednost `NULL` (tistim, ki so končali, se da iz `laps` poračunati zaostanek v krogih; za tiste brez uvrstitve je pa jasno, da so odstopili oz. niso štartali, če imajo 0 krogov)

**Comment by Zulkinho** [comment]
Najlepša vam hvala za pomoč!
Spremenila bova še kar ste naročili.

Še enkrat hvala in lep dan vam želiva.
